branches:
  only:
    - master

environment:
  nodejs_version: "10"

install:
  - choco install firefox --version 52.0.2
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

# Don't actually build.
build: off
